elageo/elageo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('contactus/',include('contactform.urls')),
    path('properties/',include('realtor.urls' ,namespace='realtor')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

elageo/main/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('',views.home, name='home'),
    path('services/',views.services,name='services'),
    path('aboutus/',views.aboutus,name='aboutus')
]

elageo/realtor/urls.py
app_name = 'realtor'

from django.urls import path
from . import views
urlpatterns = [
    path('rent_list/',views.rent_list,name='rent_list'),
    path('rent_detail/<int:id>',views.rent_detail,name='rent_detail'),
    path('sale_list/',views.sale_list,name='sale_list'),
    path('sale_detail/<int:id>',views.sale_detail,name='sale_detail'),
    path('viewing_request/<int:pid>',views.viewing_request,name='viewing_request'),
    path('viewing_reqeust_sent', views.viewing_request_sent,name='viewing_request_sent'),
]

elageo/realtor/models.py
from django.db import models

# Create your models here.

class Owner(models.Model):
    firstname = models.CharField(max_length=30)
    lastname = models.CharField(max_length=30)
    phone = models.CharField(max_length=30)
    email = models.EmailField()
    address= models.CharField(max_length=50)


    def __str__(self):
        return 'id{} name: {} {}  number: {}'.format(self.id, self.firstname,self.lastname,self.phone)




class Property(models.Model):
    PROPERTY_CHOICES = (
        ('apartment','Apartment'),
        ('house','House'),
        ('office','Office'),
        ('townhouse','Townhouse'),
        ('warehouse','Warehouse'),
        ('shop','Shop'),
        ('land','Land')
    )
    SALE_OR_RENT = (
        ('sale','Sale'),
        ('rent','Rent')
    )

    owner = models.ForeignKey(Owner, related_name='properties', on_delete = models.CASCADE)
    property_type = models.CharField(max_length = 20,choices=PROPERTY_CHOICES )
    disposal_type = models.CharField(max_length = 4, choices = SALE_OR_RENT)
    bed = models.PositiveIntegerField(default = 0)
    bath = models.PositiveIntegerField(default = 0)
    garage = models.PositiveIntegerField(default = 0,  null=True,blank=True)
    size = models.DecimalField(null=True,blank=True,max_digits=10, decimal_places=2)
    description = models.TextField(null=True,blank=True)
    location = models.CharField(max_length = 50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    lat = models.FloatField(blank=True, null=True)
    long = models.FloatField(blank=True, null=True)


    class Meta:
        ordering = ('-updated',)
        verbose_name = 'property'
        verbose_name_plural = 'properties'

    def __str__(self):
        return 'id: {} {} bedroom {} located at {} :{}' .format(self.id, self.bed,self.property_type,self.location,self.disposal_type)



class Picture(models.Model):
    img_desc = models.TextField()
    property = models.ForeignKey(Property,related_name='pictures', on_delete = models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d')

    def __str__(self):
        return 'id: {}'.format(self.id)

elageo/realtor/forms.py
from django import forms
from .models import Property

# class FilterForm(forms.ModelForm):
#     PROPERTY_CHOICES = (
#         ('all','All'),
#         ('apartment','Apartment'),
#         ('house','House'),
#         ('office','Office'),
#         ('townhouse','Townhouse'),
#         ('warehouse','Warehouse'),
#         ('shop','Shop'),
#         ('land','Land')
#     )
#     property_type = forms.ChoiceField(choices=PROPERTY_CHOICES, widget=forms.Select(attrs={'placeholder': 'property type'}))
#     class Meta:
#         model = Property
#         fields = ('bed','bath','price')




class FilterForm(forms.Form):
    PROPERTY_CHOICES = (
        ('all','All'),
        ('apartment','Apartment'),
        ('house','House'),
        ('office','Office'),
        ('townhouse','Townhouse'),
        ('warehouse','Warehouse'),
        ('shop','Shop'),
        ('land','Land')
    )
    place = forms.CharField(required=False,  widget=forms.TextInput(attrs={'placeholder': 'place'}))
    property_type = forms.ChoiceField(required=False,choices=PROPERTY_CHOICES, widget=forms.Select(attrs={'placeholder': 'property type'}))
    bed  = forms.IntegerField(required=False,  widget=forms.NumberInput(attrs={'placeholder': 'number of beds'}))
    bath = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={'placeholder': 'number of baths'}))
    price = forms.DecimalField( required=False, widget=forms.NumberInput(attrs={'placeholder': 'price less than'}))


class RequestViewingForm(forms.Form):
    name = forms.CharField(max_length=25,widget=forms.TextInput(attrs={'placeholder': 'Name'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    phone = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'placeholder': 'Phone'}))
    # comments = forms.CharField(required=False,widget=forms.Textarea(attrs={'placeholder': 'Comments'}))

elageo/realtor/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
# Create your views here.
from . models import Property
from . forms import FilterForm, RequestViewingForm



def rent_list(request):
    location_list = Property.objects.values('location').distinct()
    places = []
    for i in location_list:
        places.append(str(i['location']))

    places = sorted(places)
    current_page = 'rent_list'
    if request.method == 'POST':
        pass
        form = FilterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            fields = ('property_type','bed','bath','price')
            property_type = cd['property_type']
            bed = cd['bed']
            bath = cd['bath']
            price = cd['price']
            place = cd['place']

            if place == '':
                place = None

            if property_type == 'all' and place is None and bed is None and bath is None and price is None:
                return redirect('realtor:rent_list')
            else:
                filterquery = {}
                if place is not None:
                     filterquery.update(location=place)
                if property_type != 'all':
                    filterquery.update(property_type=property_type)
                if bed is not None:
                    filterquery.update(bed=bed)
                if  bath is not None:
                    filterquery.update(bath=bath)
                if price is not None:
                    filterquery.update(price__lte=price)
                filterquery.update(disposal_type='rent')
                rentals_list = Property.objects.filter(**filterquery).filter(available=True)
                # print(filterquery)
                # print("property_type: {} ,place:{}, bed:{},bath:{} ,price:{}".format(property_type,place,bed,bath,price))
                #------------paginator-----------------------------------------
                paginator = Paginator(rentals_list, 12) # 3 posts in each page
                page = request.GET.get('page')
                try:
                    rentals = paginator.page(page)
                except PageNotAnInteger:
                # If page is not an integer deliver the first page
                    rentals = paginator.page(1)
                except EmptyPage:
                # If page is out of range deliver last page of results
                    rentals = paginator.page(paginator.num_pages)


                return render(request,'realtor/list_rent.html',{'rentals':rentals,
                                                        'current_page':current_page,
                                                        'form':form,
                                                        'page':page,
                                                        'places':places,
        })

    else:
        form = FilterForm()
        rentals_list = Property.objects.filter(available=True,disposal_type='rent')
        #------------paginator-----------------------------------------
        paginator = Paginator(rentals_list, 12) # 3 posts in each page
        page = request.GET.get('page')
        try:
            rentals = paginator.page(page)
        except PageNotAnInteger:
        # If page is not an integer deliver the first page
            rentals = paginator.page(1)
        except EmptyPage:
        # If page is out of range deliver last page of results
            rentals = paginator.page(paginator.num_pages)

        return render(request,'realtor/list_rent.html',{'rentals':rentals,
                                                    'current_page':current_page,
                                                    'form':form,
                                                    'page':page,
                                                    'places':places,
    })

def rent_detail(request,id):
    prop = get_object_or_404(Property,id=id)
    num_pics=prop.pictures.all().count()
    num=range(num_pics)
    current_page = 'rent_list'
    if prop.lat and prop.long:
        cord = [prop.lat,prop.long]
    else:
        cord = None
    return render(request,'realtor/detail_rent.html',{'prop':prop,
                                                    'current_page':current_page,
                                                    'num':num,
                                                    'num_pics':num_pics,
                                                    'cord':cord,
    })


#----------------------------------SALE-------------------------------------------------------------------------------------



def sale_list(request):
    location_list = Property.objects.values('location').distinct()
    places = []
    for i in location_list:
        places.append(str(i['location']))

    places = sorted(places)
    current_page = 'sale_list'
    if request.method == 'POST':
        form = FilterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            fields = ('property_type','bed','bath','price')
            property_type = cd['property_type']
            bed = cd['bed']
            bath = cd['bath']
            price = cd['price']
            place = cd['place']


            if place == '':
                place = None

            if property_type == 'all' and place is None and bed is None and bath is None and price is None:
                return redirect('realtor:sale_list')
            else:
                filterquery = {}
                if place is not None:
                     filterquery.update(location=place)
                if property_type != 'all':
                    filterquery.update(property_type=property_type)
                if bed is not None:
                    filterquery.update(bed=bed)
                if  bath is not None:
                    filterquery.update(bath=bath)
                if price is not None:
                    filterquery.update(price__lte=price)
                filterquery.update(disposal_type='sale')
                sales_list = Property.objects.filter(**filterquery).filter(available=True)


                #------------paginator-----------------------------------------
                paginator = Paginator(sales_list, 12) # 3 posts in each page
                page = request.GET.get('page')
                try:
                    sales = paginator.page(page)
                except PageNotAnInteger:
                # If page is not an integer deliver the first page
                    sales = paginator.page(1)
                except EmptyPage:
                # If page is out of range deliver last page of results
                    sales = paginator.page(paginator.num_pages)

                return render(request,'realtor/list_sale.html',{'sales':sales,
                                                        'current_page':current_page,
                                                        'form':form,
                                                        'places':places,
        })

    else:
        form = FilterForm()
        sales_list = Property.objects.filter(available=True,disposal_type='sale')

        #------------paginator-----------------------------------------
        paginator = Paginator(sales_list, 12) # 3 posts in each page
        page = request.GET.get('page')
        try:
            sales = paginator.page(page)
        except PageNotAnInteger:
        # If page is not an integer deliver the first page
            sales = paginator.page(1)
        except EmptyPage:
        # If page is out of range deliver last page of results
            sales = paginator.page(paginator.num_pages)
        return render(request,'realtor/list_sale.html',{'sales':sales,
                                                    'current_page':current_page,
                                                    'form':form,
                                                    'places':places,
    })

def sale_detail(request,id):
    prop = get_object_or_404(Property,id=id)
    num_pics=prop.pictures.all().count()
    num=range(num_pics)
    current_page = 'sale_list'
    if prop.lat and prop.long:
        cord = [prop.lat,prop.long]
    else:
         cord = None
    return render(request,'realtor/detail_rent.html',{'prop':prop,
                                                    'current_page':current_page,
                                                    'num':num,
                                                    'num_pics':num_pics,
                                                    'cord':cord,
    })



def viewing_request(request, pid):
    prop = get_object_or_404(Property, id = pid)
    if request.method =='POST':
        form = RequestViewingForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            subject = "viewing request from {} ({})".format( cd['name'], cd['email'])
            sender= cd['name']
            email = cd['email']
            phone = cd['phone']
            # comments = cd['comments']
            property_of_interest = request.build_absolute_uri(reverse('realtor:rent_detail', args=(prop.id, )))
            message = '{} \n phone:{} \n email:{} \n has sent a viewing request for {}.'.format(sender,phone,email, property_of_interest)
            send_mail(subject, message, email,['carlafenu@hotmail.com',])
            # messages.success(request,'Message sent successfully')
            return redirect(reverse('realtor:viewing_request_sent'))
            # return render(request,'realtor/viewing_request_sent.html',{})

    form = RequestViewingForm()
    return render(request,'realtor/viewing_request.html',{'form':form,
                                                        })

def viewing_request_sent(request):
    return render(request,'realtor/viewing_request_sent.html',{})

elageo/realtor/templates/realtor/detail_rent.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Elageo | Rent Detail
{% endblock %}

{% block body %}

<div class="container">



<div class="col-md-8 ">
  <br>

  <div class=" heading-properties col-md-8">

    <div class="">
    <div class="col-md-6">
      <strong>{{prop.property_type|title}}</strong>
    </div>
    <div class="right-align  col-md-6">
    <i class="fas fa-tag"></i><strong> {{prop.price}}</strong>
    </div>
    </div>

    <div class="col-md-6">
      <i class="fas fa-map-marker-alt"></i>  {{prop.location}}
    </div>
</div>

  <div  >
    <div class="slider">
      <div id="about-slider">
        <div id="carousel-slider" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators visible-xs">
            {% for i in num %}
            <li data-target="#carousel-slider" data-slide-to='{{ i }}' class="active"></li>
            <!-- <li data-target="#carousel-slider" data-slide-to="1"></li>
            <li data-target="#carousel-slider" data-slide-to="2"></li> -->
          {% endfor %}
          </ol>

    {% for image in prop.pictures.all|slice:"0:1"  %}
          <div class="carousel-inner">
             <div class="item active">
              <img id ="img-wh" src='{{image.image.url}}' class="img-responsive" alt="">
            </div>
      {% endfor %}

    {% for image in prop.pictures.all|slice:"1:"  %}
      <div class="item">
        <img id ="img-wh" src='{{image.image.url}}' class="img-responsive " alt="">
      </div>
    {% endfor %}
    </div>



    <a class="left carousel-control hidden-xs" href="#carousel-slider" data-slide="prev">
      <i class="fa fa-angle-left"></i>
    </a>

    <a class=" right carousel-control hidden-xs"href="#carousel-slider" data-slide="next">
      <i class="fa fa-angle-right"></i>
    </a>
    </div> <!--/#carousel-slider-->
    </div><!--/#about-slider-->
    </div><!--/#slider-->
  </div> <!--slider -->





  <div class="heading-properties">
    <div class="col-md-4">
      <i class="fas fa-bed"></i> {{prop.bed}}
    </div>
    <div class="col-md-4">
      <i class="fas fa-bath"></i> {{prop.bath}}
    </div>
    <div class="col-md-4">
      <i class="far fa-square"></i> {{prop.size}}sqm
    </div>
  </div>

 <div class="properties-description col-md-8">
   <h4>Description</h4>
 <p>{{prop.description|linebreaks}}</p>
 </div>


<div class="request-viewing">
    <a  href= {% url 'realtor:viewing_request' pid=prop.id %} ><button class='btn btn-primary' type="button" name="button"> Request Viewing</button> </a>
</div>

{% if cord %}
<div id="mapdiv"></div>
{% endif %}
</div>



{% block script %}
<link rel="stylesheet" href= '{% static "js/leaflet.css" %}'>
<!-- <script src={% static "js/jquery.js" %}></script>
<script src={% static "js/leaflet.js" %}></script>
  <script src={% static "js/leaflet-providers.js" %}></script> -->
<script type="text/javascript">

var map;
var marker;
var objBasemaps;
var lyrOSM;
var objOverlays;
var lyrEsriImagery;
var ctlLayers;
map = L.map('mapdiv').setView({{cord|safe}}, 13);

lyrOSM = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

marker = L.circleMarker({{cord|safe}}).addTo(map)
// .bindPopup('A pretty CSS3 popup.<br> Easily customizable.')
//      .openPopup();

lyrEsriImagery = L.tileLayer.provider('Esri.WorldImagery')

objBasemaps = {
    "Open Street Maps": lyrOSM,
    "ESRI Imagery":lyrEsriImagery,
    };

ctlLayers = L.control.layers(objBasemaps, objOverlays).addTo(map);
</script>
{% endblock %}

</div>
{% endblock %}

elageo/realtor/templates/realtor/detail_sale.html
{# {% extends "base.html" %}
{% load static %}
{% block title %}
    Elageo | Sales Detail
{% endblock %}

{% block body %}
<br><br><br>

<div class="container">
<div id="detail_slider" >


<div class="slider">
  <div id="about-slider">
    <div id="carousel-slider" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators visible-xs">
        {% for i in num %}
         <li data-target="#carousel-slider" data-slide-to='{{ i }}' class="active"></li>
        <!-- <li data-target="#carousel-slider" data-slide-to="1"></li>
        <li data-target="#carousel-slider" data-slide-to="2"></li> -->
      {% endfor %}
      </ol>

{% for image in prop.pictures.all|slice:"0:1"  %}
      <div class="carousel-inner">
        <div class="item active">
          <img src='{{image.image.url}}' class="img-responsive img-w" alt="">
      </div>
          {% endfor %}
          {% for image in prop.pictures.all|slice:"1:"  %}
      <div class="item">
        <img src='{{image.image.url}}' class="img-responsive img-w" alt="">
      </div>
{% endfor %}
        </div>



<a class="left carousel-control hidden-xs" href="#carousel-slider" data-slide="prev">
  <i class="fa fa-angle-left"></i>
</a>

<a class=" right carousel-control hidden-xs"href="#carousel-slider" data-slide="next">
  <i class="fa fa-angle-right"></i>
</a>
</div> <!--/#carousel-slider-->
</div><!--/#about-slider-->
</div><!--/#slider-->
</div>

</div>


<div class="container bodydiv">
<div id='prop_detial' class="">

  <h4>For {{prop.disposal_type|title}} </h4>
  <h4>Price: Ghs <strong>{{prop.price}}</strong></h4>
  <h4>{{prop.bed}}Beds . {{prop.bath}} Baths . {{prop.property_type|title}}</h4>
  <h4>Location:{{prop.location|title}}</h4><br>
  <h4>Description</h4>
<p>{{prop.description|linebreaks}}</p>
</div>


    <div class="row">
      {% for image in prop.pictures.all  %}
        <div class="col-md-3 col-sm-6">
            <img class='thumbnail' src="{{image.image.url}} " width="300px" height="200px" alt={{image.image.url}}>
        </div>

      {% endfor %}
    </div>
    <div class="center">
    <a  href= {% url 'realtor:viewing_request' pid=prop.id %} ><button class='btn btn-primary' type="button" name="button"> Reqest Viewing</button> </a>
    </div>

    {% if cord %}
    <div id="mapdiv"></div>
    {% endif %}
</div>


{% block script %}
<!-- <script src={% static "js/jquery.js" %}></script>
<script src={% static "js/leaflet.js" %}></script>
  <script src={% static "js/leaflet-providers.js" %}></script> -->
<script type="text/javascript">

var map;
var marker;
var objBasemaps;
var lyrOSM;
var objOverlays;
var lyrEsriImagery;
var ctlLayers;
map = L.map('mapdiv').setView([5.58, -0.39], 13);

lyrOSM = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

marker = L.circleMarker([5.58, -0.39]).addTo(map)
// .bindPopup('A pretty CSS3 popup.<br> Easily customizable.')
//      .openPopup();

lyrEsriImagery = L.tileLayer.provider('Esri.WorldImagery')

objBasemaps = {
    "Open Street Maps": lyrOSM,
    "ESRI Imagery":lyrEsriImagery,
    };

ctlLayers = L.control.layers(objBasemaps, objOverlays).addTo(map);
</script>
{% endblock %}


{% endblock %} #}

elageo/realtor/templates/realtor/list_rent.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
  Elageo | Rentals
{% endblock %}

{% block body %}
<br><br>
<div class="container ">
  <div class="container">
    <form class='form-inline'  method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input class = "btn btn-primary" type="submit" name="" value="Search">
      </form>
  </div>

{% for prop in rentals %}
    <div class="prop_container col-md-4 col-sm-6">
      <div class="prop_pix thumbnail">
        {% for image in prop.pictures.all|slice:"0:1"  %}
        <a href="{% url "realtor:rent_detail" prop.id %}">  <img class='prop_img img-responsive' src="{{image.image.url}} "  alt={{image.image.url}}></a>
          {% endfor %}
          <div class=" prop_details listingfontsize">

          <table class='table'>
            <tr>
              <td><strong> {{prop.property_type|title}}</strong></td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td><i class="fas fa-tag"></i><strong> {{prop.price}}</strong></td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td><i class="fas fa-map-marker-alt"></i>  {{prop.location|title}}</td>
              <td></td>
              <td></td>
            </tr>
            <table class="table">
            <tr>
              <td class='icon_detail'><i class="fas fa-bed"></i>  {{prop.bed}} </td>
              <td class='icon_detail'><i class="fas fa-bath"></i> {{prop.bath}}</td>
              <td class='icon_detail'><i class="far fa-square"></i> {{prop.size}}sqm</td>
            </tr>
            </table>
        </table>
          </div>
          </div>
      </div>
      {% empty %}
      <div class="text-center">
          <h4>No recent listing</h4>
      </div>
{% endfor %}
</div>

<div class="container">
    <div class="paginate ">
      {% include "pagination.html" with page=rentals %}
    </div>
</div>

{% endblock %}


{% block script %}

<script type="text/javascript">
  var places = {{ places|safe}};
  $( document ).ready(function() {
    $( "#id_place" ).autocomplete({
      source: places
    });
  });
</script>
{% endblock %}

elageo/realtor/templates/realtor/list_sale.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
  Elageo | Sales
{% endblock %}

{% block body %}
<br><br>
<div class="container">
  <div class="container">
    <form class="form-inline"  method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input class = "btn btn-primary" type="submit" name="" value="search">
    </form>
  </div>



    {% for prop in sales %}s
    <div class="prop_container col-md-4 col-sm-6 centered">
      <div class="prop_pix thumbnail">
        {% for image in prop.pictures.all|slice:"0:1"  %}
        <a href="{% url "realtor:sale_detail" prop.id %}">  <img class='prop_img img-responsive' src="{{image.image.url}} "  alt={{image.image.url}}></a>
          {% endfor %}
          <div class=" prop_details listingfontsize">

          <table class='table'>
            <tr>
              <td><strong>{{prop.property_type|title}}</strong> </td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td><i class="fas fa-tag"></i><strong> {{prop.price}}</strong></td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td><i class="fas fa-map-marker-alt"></i>  {{prop.location|title}}</td>
              <td></td>
              <td></td>
            </tr>
            <table class="table">


            <tr>
              <td class='icon_detail'><i class="fas fa-bed"></i>  {{prop.bed}} </td>
              <td class='icon_detail'><i class="fas fa-bath"></i> {{prop.bath}}</td>
              <td class='icon_detail'><i class="far fa-square"></i> {{prop.size}}sqm</td>
            </tr>
            </table>
        </table>
          </div>
          </div>

      </div>
      {% empty %}

      <div class="text-center">
          <h4>No recent listing</h4>
      </div>

    {% endfor %}
  </div>

  <div class="container">
    <div class="paginate ">
      {% include "pagination.html" with page=sales %}
    </div>
  </div>

{% endblock %}



{% block script %}


<script type="text/javascript">
  var places = {{ places|safe}};
  $( document ).ready(function() {
    $( "#id_place" ).autocomplete({
      source: places
    });
  });
</script>
{% endblock %}

elageo/realtor/templates/realtor/viewing_request.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<br>
<div class="container">
<div class=" col-md-6 text-center">
  <h3>Request a viewing</h3>
</div>
</div>
<div class="container">
<div class="col-md-6">
<form class=""  method="post">
  {% csrf_token %}
  {{form|crispy}}
  <input class='btn btn-success' type="submit" name="" value="Submit">
</form>
</div>

</div>
<br><br><br><br>

{% endblock %}

elageo/realtor/templates/realtor/viewing_request_sent.html
{% extends "base.html" %}
{% block title %}
  Elageo | request sent
{% endblock %}

{% block body %}
<br>
<div class="container">


<div class="mailsent">

<br><br><br><br>
<h1> Thank you for your interest in the property..</h1>
<h2><i>We will respond to you shortly.</i></h2>
</div>
</div>

<br><br><br><br>
{% endblock %}