elageo/elageo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('contactus/',include('contactform.urls')),
    path('properties/',include('realtor.urls' ,namespace='realtor')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

elageo/main/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('',views.home, name='home'),
    path('services/',views.services,name='services'),
    path('aboutus/',views.aboutus,name='aboutus')
]

elageo/realtor/urls.py
app_name = 'realtor'

from django.urls import path
from . import views
urlpatterns = [
    path('rent_list/',views.rent_list,name='rent_list'),
    path('rent_detail/<int:id>',views.rent_detail,name='rent_detail'),
    path('sale_list/',views.sale_list,name='sale_list'),
    path('sale_detail/<int:id>',views.sale_detail,name='sale_detail'),
    path('viewing_request/<int:pid>',views.viewing_request,name='viewing_request'),
    path('viewing_reqeust_sent', views.viewing_request_sent,name='viewing_request_sent'),
]

elageo/main/models.py
from django.db import models

# Create your models here.

elageo/main/views.py
from django.shortcuts import render
from realtor.models import Property

# Create your views here.

def home(request):
    current_page = 'home'
    rentals = Property.objects.filter(available=True,disposal_type='rent').order_by('-updated')[:3]
    sale = Property.objects.filter(available=True,disposal_type='sale').order_by('-updated')[:3]
    return render(request,'main/home.html',{'current_page':current_page,
                                            'rentals':rentals,
                                            'sale':sale,
    })

def services(request):
    current_page = 'services'
    return render(request, 'main/services.html',{'current_page':current_page,})

def aboutus(request):
    current_page = 'aboutus'
    return render(request,'main/aboutus.html',{'current_page':current_page,})

elageo/main/templates/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}   {% endblock %} </title>

    <!-- Bootstrap -->

    <link href='{% static "css/bootstrap.min.css" %}' rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  	<link rel="stylesheet" href='{% static "css/font-awesome.min.css" %}'>
  	<link rel="stylesheet" href='{% static "css/animate.css" %}'>
  	<link href='{% static "css/animate.min.css" %}' rel="stylesheet">
    <link rel="stylesheet" href= '{% static "js/jquery-ui.css" %}' >
    <link rel="stylesheet" href= '{% static "js/leaflet.css" %}'>
  	<link href='{% static "css/style.css" %}' rel="stylesheet" />





  <!--Font Awesom -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
	<header id="header">
        <nav class="navbar navbar-default navbar-static-top" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                   <div class="navbar-brand">
						<a href={% url 'home' %}> <img src={% static "img/Elageo_logo-1_edit2.png" %} height='80px' width='170px'  alt="elageo_logo"> </a>
					</div>
                </div>
                <div class="navbar-collapse collapse">
					<div class="menu">

						<ul class="nav nav-tabs" role="tablist">
							<li role="presentation"><a href= {% url 'home' %} {% if current_page == 'home' %} class="active"{% endif %}>Home</a></li>
              <li role="presentation"><a href={% url 'realtor:rent_list' %} {% if current_page == 'rent_list' %} class="active"{% endif %}>Rental</a></li>
              <li role="presentation"><a href={% url 'realtor:sale_list' %} {% if current_page == 'sale_list' %} class="active"{% endif %}>Sale</a></li>
							<li role="presentation"><a href= {% url 'aboutus' %} {% if current_page == 'aboutus' %} class="active"{% endif %}>About Us</a></li>
							<li role="presentation"><a href= {% url 'services' %} {% if current_page == 'services' %} class="active"{% endif %}>Services</a></li>
							<li role="presentation"><a href= {% url 'contactus' %} {% if current_page == 'contactus' %} class="active"{% endif %}>Contact</a></li>
						</ul>
					</div>
				</div>
            </div><!--/.container-->
        </nav><!--/nav-->
    </header><!--/header-->

<div class="content">
{% block body %}

{% endblock %}
</div>

<div class="sub-footer">
  <div class="container">
    <div class="col-md-12 text-center">
      <div class="copyright">
        &copy; ELAgeo Limited. All Rights Reserved.
      </div>
    </div>
  </div>
</div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src={% static "js/jquery.js" %}></script>

    <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src={% static "js/bootstrap.min.js" %}></script>
	<script src={% static "js/wow.min.js" %}></script>
  <script  src= {% static "js/jquery-ui.js" %} type="text/javascript"></script>
  <script src={% static "js/leaflet.js" %}></script>
  <script src={% static "js/leaflet-providers.js" %}></script>
	<script>
	wow = new WOW(
	 {
		}	)
		.init();
	</script>

{% block script %}

{% endblock %}
  </body>
</html>

elageo/main/templates/pagination.html
<nav aria-label="Page navigation">
  <ul class="pager">
    {% if page.has_previous %}
    <li class='active'>
      <a  href="?page={{ page.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true"></span>Prev
      </a></li>
        {% else %}
        <li class='disabled'>
          <a  href="#" aria-label="Previous">
        <span aria-hidden="true"></span>Prev
      </a>
    </li>
    {% endif %}
    <!--<li></li>
    <li></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>-->
    <li><a href="#">Page {{ page.number }} of {{ page.paginator.num_pages }}</a></li>




    {% if page.has_next %}
    <li class='active'>

      <a href="?page={{ page.next_page_number }}" aria-label="Next">
        <span aria-hidden="true"></span>Next
      </a>next</li>
      {% else %}
      <li class='disabled'>
        <a href="#" aria-label="Next">
          <span aria-hidden="true"></span>Next
        </a></li>
        {%endif%}
  </ul>
</nav>